[theme]
primaryColor = "#f4bc47"
backgroundColor = "#1b1d22"
secondaryBackgroundColor = "#323439"
textColor = "#ffffff"
font = "sans serif"

[server]
enableStaticServing = true


# [theme]
# base="light"
# primaryColor="#573666"
# backgroundColor="#bd6161"
# textColor="#573666"


# [theme]
# base="dark"
